---
RESET_VECTOR:
  - vendor_defined: true
    isa: [machine, sec:reset]
RESET_MCAUSE_VALUES:
  - vendor_defined: true
    isa: [machine, sec:reset]
NMI_VECTOR:
  - vendor_defined: true
    isa: [machine, sec:nmi]
NMI_MCAUSE_VALUES:
  - vendor_defined: true
    isa: [machine, sec:nmi]
DEFAULT_MISA:
  - vendor_defined: false
